### ISSUE TITLE
`np.float` was a deprecated alias for the builtin `float`

### ISSUE THREAD

**Issue by hhvu0102** [BackofenLab/StoatyDive#5]
Hello,

I installed the tool through `conda` using the command `conda install -c bioconda stoatydive` as instructed at this link: https://anaconda.org/bioconda/stoatydive When I tested the example, the code failed to run:

```
StoatyDive.py -a test/broad_peaks/peaks.bed -b test/broad_peaks/reads.bed -c test/chrom_sizes.txt --peak_correction --border_penalty --turn_off_classification -o test/HV/
```

```
[START]
[NOTE] Activate Peak Correction
[NOTE] Maximal peak length 50.
[NOTE] Calculate Coverage
[NOTE] 10 peaks will be evaluated.
Traceback (most recent call last):
  File "dir/.conda/envs/StoatyDive/bin/StoatyDive.py", line 636, in <module>
    main()
  File "dir/.conda/envs/StoatyDive/bin/StoatyDive.py", line 471, in main
    nb_fit = fnb.fit_nbinom(numpy.array(peak_cov_list))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "dir/StoatyDive/StoatyDive-1.1.1/lib/fit_nbinom.py", line 32, in fit_nbinom
    infinitesimal = np.finfo(np.float).eps
                             ^^^^^^^^
  File "dir/.conda/envs/StoatyDive/lib/python3.11/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
```

Can you please suggest a way to get around with the deprecation here, or should I down-version my `numpy`?

Thank you!

**Comment by hhvu0102** [comment]
Solved. I chose the `numpy` version right before the deprecation + force `stoatydive` to use its the newest version
```
conda create -n stoatydive numpy=1.19.5
conda activate stoatydive
conda install -c bioconda stoatydive=1.1.1
```

**Comment by hhvu0102** [comment]
Solved. I chose the `numpy` version right before the deprecation + force `stoatydive` to use its the newest version
```
conda create -n stoatydive numpy=1.19.5
conda activate stoatydive
conda install -c bioconda stoatydive=1.1.1
```
